package actions

import (
	"errors"

	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop"
	"github.com/mogensen/fdfapp/models"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (ActivityParticipant)
// DB Table: Plural (activity_participants)
// Resource: Plural (ActivityParticipants)
// Path: Plural (/activity_participants)
// View Template Folder: Plural (/templates/activity_participants/)

// ActivityParticipantsResource is the resource for the ActivityParticipant model
type ActivityParticipantsResource struct {
	buffalo.Resource
}

// List gets all ActivityParticipants. This function is mapped to the path
// GET /activity_participants
func (v ActivityParticipantsResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.New("no transaction found")
	}

	activityParticipants := &models.ActivityParticipants{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all ActivityParticipants from the DB
	if err := q.All(activityParticipants); err != nil {
		return err
	}

	// Add the paginator to the context so it can be used in the template.
	c.Set("pagination", q.Paginator)

	return c.Render(200, r.Auto(c, activityParticipants))
}

// Show gets the data for one ActivityParticipant. This function is mapped to
// the path GET /activity_participants/{activity_participant_id}
func (v ActivityParticipantsResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.New("no transaction found")
	}

	// Allocate an empty ActivityParticipant
	activityParticipant := &models.ActivityParticipant{}

	// To find the ActivityParticipant the parameter activity_participant_id is used.
	if err := tx.Find(activityParticipant, c.Param("activity_participant_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, activityParticipant))
}

// New renders the form for creating a new ActivityParticipant.
// This function is mapped to the path GET /activity_participants/new
func (v ActivityParticipantsResource) New(c buffalo.Context) error {
	return c.Render(200, r.Auto(c, &models.ActivityParticipant{}))
}

// Create adds a ActivityParticipant to the DB. This function is mapped to the
// path POST /activity_participants
func (v ActivityParticipantsResource) Create(c buffalo.Context) error {
	// Allocate an empty ActivityParticipant
	activityParticipant := &models.ActivityParticipant{}

	// Bind activityParticipant to the html form elements
	if err := c.Bind(activityParticipant); err != nil {
		return err
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.New("no transaction found")
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(activityParticipant)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the new.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, activityParticipant))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", T.Translate(c, "activityParticipant.created.success"))
	// and redirect to the activity_participants index page
	return c.Render(201, r.Auto(c, activityParticipant))
}

// Edit renders a edit form for a ActivityParticipant. This function is
// mapped to the path GET /activity_participants/{activity_participant_id}/edit
func (v ActivityParticipantsResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.New("no transaction found")
	}

	// Allocate an empty ActivityParticipant
	activityParticipant := &models.ActivityParticipant{}

	if err := tx.Find(activityParticipant, c.Param("activity_participant_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, activityParticipant))
}

// Update changes a ActivityParticipant in the DB. This function is mapped to
// the path PUT /activity_participants/{activity_participant_id}
func (v ActivityParticipantsResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.New("no transaction found")
	}

	// Allocate an empty ActivityParticipant
	activityParticipant := &models.ActivityParticipant{}

	if err := tx.Find(activityParticipant, c.Param("activity_participant_id")); err != nil {
		return c.Error(404, err)
	}

	// Bind ActivityParticipant to the html form elements
	if err := c.Bind(activityParticipant); err != nil {
		return err
	}

	verrs, err := tx.ValidateAndUpdate(activityParticipant)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the edit.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, activityParticipant))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", T.Translate(c, "activityParticipant.updated.success"))
	// and redirect to the activity_participants index page
	return c.Render(200, r.Auto(c, activityParticipant))
}

// Destroy deletes a ActivityParticipant from the DB. This function is mapped
// to the path DELETE /activity_participants/{activity_participant_id}
func (v ActivityParticipantsResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.New("no transaction found")
	}

	// Allocate an empty ActivityParticipant
	activityParticipant := &models.ActivityParticipant{}

	// To find the ActivityParticipant the parameter activity_participant_id is used.
	if err := tx.Find(activityParticipant, c.Param("activity_participant_id")); err != nil {
		return c.Error(404, err)
	}

	if err := tx.Destroy(activityParticipant); err != nil {
		return err
	}

	// If there are no errors set a flash message
	c.Flash().Add("success", T.Translate(c, "activityParticipant.destroyed.success"))
	// Redirect to the activity_participants index page
	return c.Render(200, r.Auto(c, activityParticipant))
}
