package actions

import (
	"errors"
	"fmt"

	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop/v5"
	"github.com/mogensen/fdfapp/models"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (ClassMembership)
// DB Table: Plural (class_memberships)
// Resource: Plural (ClassMemberships)
// Path: Plural (/class_memberships)
// View Template Folder: Plural (/templates/class_memberships/)

// ClassMembershipsResource is the resource for the ClassMembership model
type ClassMembershipsResource struct {
	buffalo.Resource
}

// Create adds a ClassMembership to the DB. This function is mapped to the
// path POST /class_memberships
func (v ClassMembershipsResource) Create(c buffalo.Context) error {
	// Allocate an empty ClassMembership
	classMembership := &models.ClassMembership{}

	// Bind classMembership to the html form elements
	if err := c.Bind(classMembership); err != nil {
		return err
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.New("no transaction found")
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(classMembership)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the new.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, classMembership))
	}

	participant := &models.Participant{}

	// To find the Participant the parameter participant_id is used.
	if err := tx.Eager().Find(participant, classMembership.ParticipantID); err != nil {
		return c.Error(404, err)
	}

	// If there are no errors set a success message
	c.Flash().Add("success", T.Translate(c, "classMembership.created.success"))
	// and redirect to the class_memberships index page
	x := fmt.Sprintf("/participants/%s", classMembership.ParticipantID)
	return c.Redirect(302, x)
}

// Destroy deletes a ClassMembership from the DB. This function is mapped
// to the path DELETE /class_memberships/{class_membership_id}
func (v ClassMembershipsResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.New("no transaction found")
	}

	// Allocate an empty ClassMembership
	classMembership := &models.ClassMembership{}

	// To find the ClassMembership the parameter class_membership_id is used.
	if err := tx.Find(classMembership, c.Param("class_membership_id")); err != nil {
		return c.Error(404, err)
	}

	if err := tx.Destroy(classMembership); err != nil {
		return err
	}

	// If there are no errors set a flash message
	c.Flash().Add("success", T.Translate(c, "classMembership.destroyed.success"))
	// Redirect to the class_memberships index page
	x := fmt.Sprintf("/participants/%s", classMembership.ParticipantID)
	return c.Redirect(302, x)
}
