package actions

import (
	"encoding/base64"
	"fmt"
	"io/ioutil"
	"log"
	"net/http"

	"github.com/disintegration/imaging"
	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop"
	"github.com/gofrs/uuid"
	"github.com/mogensen/fdfapp/models"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (ParticipantsImage)
// DB Table: Plural (participants_images)
// Resource: Plural (ParticipantsImages)
// Path: Plural (/participants_images)
// View Template Folder: Plural (/templates/participants_images/)

// ParticipantsImagesResource is the resource for the ParticipantsImage model
type ParticipantsImagesResource struct {
	buffalo.Resource
}

// List gets all ParticipantsImages. This function is mapped to the path
// GET /participants_images
func (v ParticipantsImagesResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	participantsImages := &models.ParticipantsImages{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all ParticipantsImages from the DB
	if err := q.All(participantsImages); err != nil {
		return err
	}

	// Add the paginator to the context so it can be used in the template.
	c.Set("pagination", q.Paginator)

	return c.Render(200, r.Auto(c, participantsImages))
}

// Show gets the data for one ParticipantsImage. This function is mapped to
// the path GET /participants_images/{participants_image_id}
func (v ParticipantsImagesResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty ParticipantsImage
	participantsImage := &models.ParticipantsImage{}

	// To find the ParticipantsImage the parameter participants_image_id is used.
	if err := tx.Find(participantsImage, c.Param("participants_image_id")); err != nil {
		return c.Error(404, err)
	}
	p, err := base64.StdEncoding.DecodeString(string(participantsImage.ImageData))
	if err != nil {
		http.Error(c.Response(), "internal error", 500)
		return err
	}

	c.Response().Write(p)
	return nil
}

// New renders the form for creating a new ParticipantsImage.
// This function is mapped to the path GET /participants_images/new
func (v ParticipantsImagesResource) New(c buffalo.Context) error {

	pID, err := uuid.FromString(c.Param("participant_id"))
	if err != nil {
		return err
	}

	pi := &models.ParticipantsImage{
		ParticipantID: pID,
	}

	return c.Render(200, r.Auto(c, pi))
}

// Create adds a ParticipantsImage to the DB. This function is mapped to the
// path POST /participants_images
func (v ParticipantsImagesResource) Create(c buffalo.Context) error {
	// Allocate an empty ParticipantsImage
	participantsImage := &models.ParticipantsImage{}

	// Bind participantsImage to the html form elements
	if err := c.Bind(participantsImage); err != nil {
		return err
	}

	if !participantsImage.Image.Valid() {
		return nil
	}

	img, err := imaging.Decode(participantsImage.Image.File)
	if err != nil {
		return err
	}
	dstImageFit := imaging.Fill(img, 300, 300, imaging.Center, imaging.Lanczos)

	err = imaging.Save(dstImageFit, "/tmp/fdf.jpg")
	if err != nil {
		log.Fatalf("failed to save image: %v", err)
	}
	bytes, err := ioutil.ReadFile("/tmp/fdf.jpg")
	if err != nil {
		log.Fatalf("failed to read image: %v", err)
	}
	participantsImage.ImageData = []byte(base64.StdEncoding.EncodeToString(bytes))

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(participantsImage)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the new.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, participantsImage))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", T.Translate(c, "participantsImage.created.success"))
	// and redirect to the participant show page
	return c.Redirect(302, "/participants/"+participantsImage.ParticipantID.String())
}

// Edit renders a edit form for a ParticipantsImage. This function is
// mapped to the path GET /participants_images/{participants_image_id}/edit
func (v ParticipantsImagesResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty ParticipantsImage
	participantsImage := &models.ParticipantsImage{}

	if err := tx.Find(participantsImage, c.Param("participants_image_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, participantsImage))
}

// Update changes a ParticipantsImage in the DB. This function is mapped to
// the path PUT /participants_images/{participants_image_id}
func (v ParticipantsImagesResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty ParticipantsImage
	participantsImage := &models.ParticipantsImage{}

	if err := tx.Find(participantsImage, c.Param("participants_image_id")); err != nil {
		return c.Error(404, err)
	}

	// Bind ParticipantsImage to the html form elements
	if err := c.Bind(participantsImage); err != nil {
		return err
	}

	img, err := imaging.Decode(participantsImage.Image.File)
	if err != nil {
		return err
	}
	dstImageFit := imaging.Fill(img, 300, 300, imaging.Center, imaging.Lanczos)

	err = imaging.Save(dstImageFit, "/tmp/fdf.jpg")
	if err != nil {
		log.Fatalf("failed to save image: %v", err)
	}
	bytes, err := ioutil.ReadFile("/tmp/fdf.jpg")
	if err != nil {
		log.Fatalf("failed to read image: %v", err)
	}
	participantsImage.ImageData = []byte(base64.StdEncoding.EncodeToString(bytes))

	verrs, err := tx.ValidateAndUpdate(participantsImage)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the edit.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, participantsImage))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", T.Translate(c, "participantsImage.updated.success"))
	// and redirect to the participants_images index page
	return c.Redirect(302, "/participants/"+participantsImage.ParticipantID.String())
}

// Destroy deletes a ParticipantsImage from the DB. This function is mapped
// to the path DELETE /participants_images/{participants_image_id}
func (v ParticipantsImagesResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty ParticipantsImage
	participantsImage := &models.ParticipantsImage{}

	// To find the ParticipantsImage the parameter participants_image_id is used.
	if err := tx.Find(participantsImage, c.Param("participants_image_id")); err != nil {
		return c.Error(404, err)
	}

	if err := tx.Destroy(participantsImage); err != nil {
		return err
	}

	// If there are no errors set a flash message
	c.Flash().Add("success", T.Translate(c, "participantsImage.destroyed.success"))
	// Redirect to the participants_images index page
	return c.Render(200, r.Auto(c, participantsImage))
}
